"""
Agent 7: Doc Generator Agent

Synthesises all pipeline outputs into:
  - state.final_doc          → onboarding.md  (human-oriented)
  - state.agent_context_md   → agent_context.md (AI coding agent-oriented)
  - state.complexity_report_json → complexity_report.json

Design invariants:
  - Zero new analysis. All data sourced from ArchaeonState as-is.
  - Every section generator is independently wrapped in try/except.
    One section failing never prevents the rest from rendering.
  - agent_context.md is concise by design: tables and bullets, not prose.
    Target audience is an LLM's system prompt, not a human reader.
"""

import json
import logging
from datetime import datetime
from typing import Optional

from src.state import ArchaeonState

logger = logging.getLogger(__name__)


# ═══════════════════════════════════════════════════════════════════════════
# Shared helpers
# ═══════════════════════════════════════════════════════════════════════════

def _repo_name(state: ArchaeonState) -> str:
    if state.repo_name:
        return state.repo_name
    try:
        parts = state.repo_url.rstrip("/").split("/")
        return parts[-1] if parts else "unknown-repo"
    except Exception:
        return "unknown-repo"


def _repo_owner(state: ArchaeonState) -> str:
    if state.owner:
        return state.owner
    try:
        parts = state.repo_url.rstrip("/").split("/")
        return parts[-2] if len(parts) >= 2 else "unknown"
    except Exception:
        return "unknown"


def _default_branch(state: ArchaeonState) -> str:
    return state.default_branch or "main"


def _language_breakdown(state: ArchaeonState) -> dict:
    """
    Count files per language from file_manifest.
    file_manifest contains FileMetadata objects — access .language directly.
    """
    counts: dict = {}
    for f in state.file_manifest:
        lang = f.language if hasattr(f, "language") else f.get("language", "Unknown")
        counts[lang] = counts.get(lang, 0) + 1
    return dict(sorted(counts.items(), key=lambda x: x[1], reverse=True))


def _risk_counts(state: ArchaeonState) -> dict:
    counts = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0}
    for cs in state.complexity_scores.values():
        level = getattr(cs, "risk_level", "LOW")
        if level in counts:
            counts[level] += 1
    return counts


def _in_degree_map(state: ArchaeonState) -> dict:
    if state.dependency_graph is None:
        return {}
    return dict(state.dependency_graph.in_degree())


def _out_degree_map(state: ArchaeonState) -> dict:
    if state.dependency_graph is None:
        return {}
    return dict(state.dependency_graph.out_degree())


def _short_path(path: str, max_parts: int = 3) -> str:
    parts = path.replace("\\", "/").split("/")
    return "/".join(parts[-max_parts:]) if len(parts) > max_parts else path


def _timestamp() -> str:
    return datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")


def _total_functions(state: ArchaeonState) -> int:
    total = 0
    for st in state.symbol_tables.values():
        fns = st.functions if hasattr(st, "functions") else st.get("functions", [])
        total += len(fns)
    return total


def _total_classes(state: ArchaeonState) -> int:
    total = 0
    for st in state.symbol_tables.values():
        cls = st.classes if hasattr(st, "classes") else st.get("classes", [])
        total += len(cls)
    return total


def _get_fn_name(fn) -> str:
    return fn.name if hasattr(fn, "name") else fn.get("name", "?")


def _get_fn_complexity(fn) -> float:
    return (fn.complexity if hasattr(fn, "complexity") else fn.get("complexity", 0)) or 0


def _get_classes(st) -> list:
    return st.classes if hasattr(st, "classes") else st.get("classes", [])


def _get_class_name(cls) -> str:
    return cls.name if hasattr(cls, "name") else cls.get("name", "?")


def _get_class_methods(cls) -> list:
    return cls.methods if hasattr(cls, "methods") else cls.get("methods", [])


# ═══════════════════════════════════════════════════════════════════════════
# onboarding.md — section generators
# ═══════════════════════════════════════════════════════════════════════════

def _build_header(state: ArchaeonState) -> str:
    repo = _repo_name(state)
    branch = _default_branch(state)
    return (
        f"# {repo} — Architecture Overview\n\n"
        f"**Generated by Project Gnosis (Code Archaeology Agent)**  \n"
        f"**Repository:** {state.repo_url}  \n"
        f"**Branch:** {branch}  \n"
        f"**Generated:** {_timestamp()}  \n"
        f"**Analysis Mode:** {state.analysis_mode}\n\n"
        f"---\n\n"
    )


def _build_project_summary(state: ArchaeonState) -> str:
    lang_breakdown = _language_breakdown(state)
    risk = _risk_counts(state)

    lang_str = ", ".join(
        f"{lang} ({count} files)"
        for lang, count in list(lang_breakdown.items())[:5]
    )

    return (
        f"## Project Summary\n\n"
        f"**{_repo_name(state)}** contains **{state.files_analyzed}** analyzed files "
        f"({state.files_discovered} discovered).\n\n"
        f"**Languages:** {lang_str or 'Unknown'}  \n"
        f"**Total functions extracted:** {_total_functions(state)}  \n"
        f"**Risk distribution:** {risk['CRITICAL']} CRITICAL · {risk['HIGH']} HIGH · "
        f"{risk['MEDIUM']} MEDIUM · {risk['LOW']} LOW\n\n"
    )


def _build_repository_statistics(state: ArchaeonState) -> str:
    lang_breakdown = _language_breakdown(state)
    risk = _risk_counts(state)

    g = state.dependency_graph
    graph_nodes = g.number_of_nodes() if g else 0
    graph_edges = g.number_of_edges() if g else 0

    top_lang = list(lang_breakdown.keys())[0] if lang_breakdown else "Unknown"
    top_lang_pct = (
        round(lang_breakdown[top_lang] / max(state.files_analyzed, 1) * 100)
        if lang_breakdown else 0
    )

    rows = [
        ("Files discovered", state.files_discovered),
        ("Files analyzed", state.files_analyzed),
        ("Analysis mode", state.analysis_mode),
        ("Primary language", f"{top_lang} ({top_lang_pct}%)"),
        ("Total functions", _total_functions(state)),
        ("Total classes", _total_classes(state)),
        ("Dependency graph nodes", graph_nodes),
        ("Dependency graph edges", graph_edges),
        ("Circular dependencies", len(state.circular_deps)),
        ("CRITICAL risk files", risk["CRITICAL"]),
        ("HIGH risk files", risk["HIGH"]),
    ]

    table = "| Metric | Value |\n|--------|-------|\n"
    table += "\n".join(f"| {k} | {v} |" for k, v in rows)
    return f"## Repository Statistics\n\n{table}\n\n"


def _build_architecture_map(state: ArchaeonState) -> str:
    if state.dependency_graph is None:
        return "## Architecture Map\n\n*Dependency graph not available.*\n\n"

    in_deg = dict(state.dependency_graph.in_degree())
    if not in_deg:
        return "## Architecture Map\n\n*No dependency data.*\n\n"

    top = sorted(in_deg.items(), key=lambda x: x[1], reverse=True)[:15]

    lines = [
        "## Architecture Map",
        "",
        "Top files by dependency in-degree (how many other files import each one):",
        "",
        "| File Path | In-Degree (Imports) | Risk Level |",
        "| :--- | :---: | :---: |",
    ]
    for path, deg in top:
        short = _short_path(path)
        cs = state.complexity_scores.get(path)
        risk = getattr(cs, "risk_level", "LOW")
        lines.append(f"| `{short}` | {deg} | **{risk}** |")
    lines.append("")
    return "\n".join(lines) + "\n"


def _build_core_components(state: ArchaeonState) -> str:
    if state.dependency_graph is None:
        return "## Core Components\n\n*Dependency graph not available.*\n\n"

    in_deg = dict(state.dependency_graph.in_degree())
    top = sorted(in_deg.items(), key=lambda x: x[1], reverse=True)
    top = [(fp, d) for fp, d in top if d > 0][:20]

    lines = ["## Core Components", ""]

    for fp, deg in top:
        short = _short_path(fp)
        cs = state.complexity_scores.get(fp)
        risk = getattr(cs, "risk_level", "?") if cs else "?"
        avg_cc = getattr(cs, "avg_complexity", 0.0) if cs else 0.0

        preds = list(state.dependency_graph.predecessors(fp))
        succs = list(state.dependency_graph.successors(fp))

        lines.append(f"### `{short}`")
        lines.append(f"**Risk:** {risk} · **In-degree:** {deg} · **Avg CC:** {avg_cc:.1f}")
        if succs:
            lines.append(f"**Depends on:** {', '.join(_short_path(s) for s in succs[:6])}")
        if preds:
            lines.append(f"**Depended on by:** {', '.join(_short_path(p) for p in preds[:6])}")

        explanation = state.explanations.get(fp)
        if explanation:
            lines.append("")
            lines.append(explanation.strip())

        lines.append("")

    return "\n".join(lines) + "\n"


def _build_tech_debt_report(state: ArchaeonState) -> str:
    lines = ["## Tech Debt Report", ""]

    # Circular dependencies
    if state.circular_deps:
        lines += ["### Circular Dependencies", ""]
        lines.append("| Cycle # | Dependencies Cycle | Length |")
        lines.append("| :---: | :--- | :---: |")
        for i, cycle in enumerate(state.circular_deps[:10], 1):
            cycle_str = " → ".join(f"`{_short_path(f)}`" for f in cycle) + f" → `{_short_path(cycle[0])}`"
            lines.append(f"| {i} | {cycle_str} | {len(cycle)} |")
        lines.append("")
    else:
        lines += ["### Circular Dependencies", "", "No circular dependencies detected.", ""]

    # CRITICAL files
    critical = [
        (fp, cs) for fp, cs in state.complexity_scores.items()
        if getattr(cs, "risk_level", "") == "CRITICAL"
    ]
    if critical:
        lines += ["### CRITICAL Risk Files", ""]
        lines.append("| File | Max CC | Avg CC | Coupling | Notes |")
        lines.append("|------|--------|--------|----------|-------|")
        for fp, cs in sorted(
            critical, key=lambda x: getattr(x[1], "max_complexity", 0), reverse=True
        )[:15]:
            short = _short_path(fp)
            max_cc = getattr(cs, "max_complexity", 0)
            avg_cc = getattr(cs, "avg_complexity", 0.0)
            coupling = getattr(cs, "coupling_score", 0)
            notes = []
            if getattr(cs, "parse_error", False):        # actual field name
                notes.append("parse error")
            if getattr(cs, "is_in_circular_dep", False): # actual field name
                notes.append("in cycle")
            if max_cc >= 21:
                notes.append(f"CC={max_cc:.0f}")
            lines.append(
                f"| `{short}` | {max_cc:.0f} | {avg_cc:.1f} | {coupling} | "
                f"{', '.join(notes) or '—'} |"
            )
        lines.append("")

    # Parse errors — uses score.parse_error (actual field name)
    parse_errors = [
        fp for fp, cs in state.complexity_scores.items()
        if getattr(cs, "parse_error", False)
    ]
    if parse_errors:
        lines += ["### Parse Errors", ""]
        lines.append("| ID | File Path | Status |")
        lines.append("| :---: | :--- | :---: |")
        for i, fp in enumerate(parse_errors[:10], 1):
            lines.append(f"| {i} | `{_short_path(fp)}` | ⚠️ PARSE ERROR |")
        lines.append("")

    # High complexity functions — uses score.function_scores dict (actual field)
    high_cc_funcs = []
    for fp, cs in state.complexity_scores.items():
        fn_scores = getattr(cs, "function_scores", {}) or {}
        for fn_name, complexity in fn_scores.items():
            if (complexity or 0) >= 10:
                high_cc_funcs.append((fp, fn_name, complexity))
    high_cc_funcs.sort(key=lambda x: x[2], reverse=True)

    lines += ["### High Complexity Functions", ""]
    if high_cc_funcs:
        lines.append("| File | Function | Cyclomatic Complexity |")
        lines.append("|------|----------|-----------------------|")
        for fp, fn_name, cc in high_cc_funcs[:20]:
            lines.append(f"| `{_short_path(fp)}` | `{fn_name}` | {cc} |")
    else:
        lines.append("No functions with cyclomatic complexity ≥ 10 detected.")
    lines.append("")

    return "\n".join(lines) + "\n"


def _build_reading_order(state: ArchaeonState) -> str:
    lines = ["## Suggested Reading Order", ""]

    if state.circular_deps:
        lines.append(
            "⚠️ **Circular dependencies detected.** "
            "A strict topological order does not exist. The list below is approximate."
        )
        lines.append("")

    order = state.topological_order or []
    if order:
        lines.append("| Order | File Path | Risk Level |")
        lines.append("| :---: | :--- | :---: |")
        for i, fp in enumerate(order[:25], 1):
            short = _short_path(fp)
            cs = state.complexity_scores.get(fp)
            risk = getattr(cs, "risk_level", "LOW")
            lines.append(f"| {i} | `{short}` | **{risk}** |")
        if len(order) > 25:
            lines.append(f"\n*...and {len(order) - 25} more files.*")
    else:
        lines.append("*Reading order not available.*")

    lines.append("")
    return "\n".join(lines) + "\n"


def _build_footer(state: ArchaeonState) -> str:
    return (
        f"---\n\n"
        f"*Generated by Project Gnosis (Code Archaeology Agent) · {_timestamp()}*  \n"
        f"*Analyzed {state.files_analyzed} of {state.files_discovered} files · "
        f"{state.analysis_mode} mode*\n"
    )


# ═══════════════════════════════════════════════════════════════════════════
# agent_context.md — section generators
# ═══════════════════════════════════════════════════════════════════════════

def _ac_system_overview(state: ArchaeonState) -> str:
    repo = _repo_name(state)
    lang_breakdown = _language_breakdown(state)
    risk = _risk_counts(state)

    top_langs = ", ".join(
        f"{l} ({c} files)" for l, c in list(lang_breakdown.items())[:3]
    )
    g = state.dependency_graph
    graph_edges = g.number_of_edges() if g else 0
    graph_nodes = g.number_of_nodes() if g else 0

    return (
        f"## System Overview\n\n"
        f"**Repository:** `{repo}` · {state.repo_url}  \n"
        f"**Branch:** {_default_branch(state)}  \n"
        f"**Files:** {state.files_analyzed} analyzed of {state.files_discovered} discovered · "
        f"Mode: {state.analysis_mode}  \n"
        f"**Languages:** {top_langs or 'Unknown'}  \n"
        f"**Functions:** {_total_functions(state)} · "
        f"**Dependency edges:** {graph_edges} across {graph_nodes} modules  \n"
        f"**Risk:** {risk['CRITICAL']} CRITICAL · {risk['HIGH']} HIGH · "
        f"{risk['MEDIUM']} MEDIUM · {risk['LOW']} LOW\n\n"
    )


def _ac_critical_entry_points(state: ArchaeonState) -> str:
    lines = ["## Critical Entry Points", ""]

    if state.dependency_graph is None:
        lines += ["*Dependency graph not available.*", ""]
        return "\n".join(lines) + "\n"

    in_deg = dict(state.dependency_graph.in_degree())
    out_deg = dict(state.dependency_graph.out_degree())

    entry_points = [
        fp for fp, ind in in_deg.items()
        if ind == 0 and out_deg.get(fp, 0) > 0
    ]
    entry_points.sort(key=lambda fp: out_deg.get(fp, 0), reverse=True)

    if not entry_points and state.topological_order:
        entry_points = [fp for fp in state.topological_order if in_deg.get(fp, 0) == 0][:5]

    if not entry_points:
        all_nodes = sorted(out_deg.items(), key=lambda x: x[1], reverse=True)
        entry_points = [fp for fp, d in all_nodes if d > 0][:5]

    if not entry_points:
        lines += ["*No entry points identified. All files may be in cycles.*", ""]
        return "\n".join(lines) + "\n"

    lines.append("Files not imported by any other file. Execution likely begins here.")
    lines.append("")

    for fp in entry_points[:10]:
        short = _short_path(fp)
        out = out_deg.get(fp, 0)
        cs = state.complexity_scores.get(fp)
        risk_tag = f" · risk: {getattr(cs, 'risk_level', '?')}" if cs else ""
        lines.append(f"- `{short}` — imports {out} module(s){risk_tag}")

    lines.append("")
    return "\n".join(lines) + "\n"


def _ac_core_components(state: ArchaeonState) -> str:
    lines = ["## Core Components", ""]

    if state.dependency_graph is None:
        lines += ["*Dependency graph not available.*", ""]
        return "\n".join(lines) + "\n"

    in_deg = dict(state.dependency_graph.in_degree())
    top = [
        (fp, d)
        for fp, d in sorted(in_deg.items(), key=lambda x: x[1], reverse=True)
        if d > 0
    ][:10]

    if not top:
        lines += ["*No dependency data available.*", ""]
        return "\n".join(lines) + "\n"

    lines.append("Ranked by how many other files import them. High in-degree = high blast radius.")
    lines.append("")
    lines.append("| Rank | File | In-degree | Risk | Avg CC |")
    lines.append("|------|------|-----------|------|--------|")

    for i, (fp, deg) in enumerate(top, 1):
        short = _short_path(fp)
        cs = state.complexity_scores.get(fp)
        risk = getattr(cs, "risk_level", "?") if cs else "?"
        avg_cc = f"{getattr(cs, 'avg_complexity', 0.0):.1f}" if cs else "?"
        lines.append(f"| {i} | `{short}` | {deg} | {risk} | {avg_cc} |")

    lines.append("")
    return "\n".join(lines) + "\n"


def _ac_architectural_relationships(state: ArchaeonState) -> str:
    lines = ["## Architectural Relationships", ""]

    if state.dependency_graph is None:
        lines += ["*Dependency graph not available.*", ""]
        return "\n".join(lines) + "\n"

    in_deg = dict(state.dependency_graph.in_degree())
    top = [
        (fp, d)
        for fp, d in sorted(in_deg.items(), key=lambda x: x[1], reverse=True)
        if d > 0
    ][:6]

    if not top:
        lines += ["*No significant dependency chains found.*", ""]
        return "\n".join(lines) + "\n"

    lines.append("Direct relationships for the most-imported modules:")
    lines.append("")

    for fp, deg in top:
        short = _short_path(fp)
        preds = list(state.dependency_graph.predecessors(fp))
        succs = list(state.dependency_graph.successors(fp))
        lines.append(f"**`{short}`** — imported by {deg} file(s)")
        if succs:
            lines.append(
                f"  - Imports: {', '.join(f'`{_short_path(s)}`' for s in succs[:6])}"
            )
        if preds:
            overflow = f" *(+{len(preds)-6} more)*" if len(preds) > 6 else ""
            lines.append(
                f"  - Imported by: {', '.join(f'`{_short_path(p)}`' for p in preds[:6])}"
                + overflow
            )
        lines.append("")

    return "\n".join(lines) + "\n"


def _ac_high_risk_areas(state: ArchaeonState) -> str:
    lines = ["## High Risk Areas", ""]

    if not state.complexity_scores:
        lines += ["*Complexity scores not available.*", ""]
        return "\n".join(lines) + "\n"

    risky = [
        (fp, cs) for fp, cs in state.complexity_scores.items()
        if getattr(cs, "risk_level", "") in ("CRITICAL", "HIGH")
    ]

    if not risky:
        lines += ["No CRITICAL or HIGH risk files detected.", ""]
        return "\n".join(lines) + "\n"

    lines.append("**Do not modify without understanding the full dependency surface.**")
    lines.append("")
    lines.append("| File | Risk | Max CC | Coupling | In-degree |")
    lines.append("|------|------|--------|----------|-----------|")

    in_deg = _in_degree_map(state)
    risky.sort(key=lambda x: (
        0 if getattr(x[1], "risk_level", "") == "CRITICAL" else 1,
        -getattr(x[1], "max_complexity", 0),
    ))

    for fp, cs in risky[:15]:
        short = _short_path(fp)
        risk = getattr(cs, "risk_level", "?")
        max_cc = getattr(cs, "max_complexity", 0)
        coupling = getattr(cs, "coupling_score", 0)
        deg = in_deg.get(fp, 0)
        lines.append(f"| `{short}` | {risk} | {max_cc:.0f} | {coupling} | {deg} |")

    lines.append("")
    return "\n".join(lines) + "\n"


def _ac_circular_dependencies(state: ArchaeonState) -> str:
    lines = ["## Circular Dependencies", ""]

    if not state.circular_deps:
        lines += ["No circular dependencies detected.", ""]
        return "\n".join(lines) + "\n"

    n = len(state.circular_deps)
    lines.append(
        f"**{n} cycle(s) detected.** "
        "All files in cycles are marked CRITICAL risk. "
        "Resolve cycles before refactoring any member file."
    )
    lines.append("")

    for cycle in state.circular_deps[:10]:
        chain = " → ".join(f"`{_short_path(f)}`" for f in cycle)
        chain += f" → `{_short_path(cycle[0])}`"
        lines.append(f"- {chain}")

    if n > 10:
        lines.append(f"\n*...and {n - 10} more cycles.*")

    lines.append("")
    return "\n".join(lines) + "\n"


def _ac_important_domain_objects(state: ArchaeonState) -> str:
    lines = ["## Important Domain Objects", ""]

    if not state.symbol_tables:
        lines += ["*Symbol tables not available.*", ""]
        return "\n".join(lines) + "\n"

    in_deg = _in_degree_map(state)
    all_classes = []

    for fp, st in state.symbol_tables.items():
        for cls in _get_classes(st):
            cls_name = _get_class_name(cls)
            method_count = len(_get_class_methods(cls))
            all_classes.append((in_deg.get(fp, 0), fp, cls_name, method_count))

    all_classes.sort(key=lambda x: x[0], reverse=True)

    if not all_classes:
        lines += ["*No class definitions found.*", ""]
        return "\n".join(lines) + "\n"

    lines.append("Classes ranked by the import importance of their containing file:")
    lines.append("")

    for deg, fp, cls_name, method_count in all_classes[:15]:
        short = _short_path(fp)
        dep_note = f" · file imported by {deg} module(s)" if deg > 0 else ""
        lines.append(f"- **`{cls_name}`** in `{short}` — {method_count} method(s){dep_note}")

    lines.append("")
    return "\n".join(lines) + "\n"


def _ac_change_impact_guide(state: ArchaeonState) -> str:
    lines = ["## Change Impact Guide", ""]

    if state.dependency_graph is None:
        lines += ["*Dependency graph not available.*", ""]
        return "\n".join(lines) + "\n"

    in_deg = dict(state.dependency_graph.in_degree())
    top = [
        (fp, d)
        for fp, d in sorted(in_deg.items(), key=lambda x: x[1], reverse=True)
        if d > 0
    ][:8]

    if not top:
        lines += ["*No dependency data to derive impact from.*", ""]
        return "\n".join(lines) + "\n"

    lines.append("When modifying a file below, verify all direct dependents still behave correctly.")
    lines.append("")

    for fp, deg in top:
        short = _short_path(fp)
        preds = list(state.dependency_graph.predecessors(fp))
        cs = state.complexity_scores.get(fp)
        risk = getattr(cs, "risk_level", "?") if cs else "?"

        lines.append(f"**If modifying `{short}` ({risk} risk · {deg} direct dependent(s)):**")
        for p in preds[:7]:
            lines.append(f"  - `{_short_path(p)}`")
        if len(preds) > 7:
            lines.append(f"  - *...and {len(preds) - 7} more*")
        lines.append("")

    return "\n".join(lines) + "\n"


def _ac_safe_starting_points(state: ArchaeonState) -> str:
    lines = ["## Safe Starting Points", ""]

    if not state.complexity_scores:
        lines += ["*Complexity scores not available.*", ""]
        return "\n".join(lines) + "\n"

    in_deg = _in_degree_map(state)
    out_deg = _out_degree_map(state)

    low_risk = [
        (fp, cs) for fp, cs in state.complexity_scores.items()
        if getattr(cs, "risk_level", "") == "LOW"
        and not getattr(cs, "parse_error", False)   # actual field name
    ]
    low_risk.sort(key=lambda x: (in_deg.get(x[0], 0), out_deg.get(x[0], 0)))

    if not low_risk:
        lines += ["*No LOW risk files identified.*", ""]
        return "\n".join(lines) + "\n"

    lines.append("Low complexity, low coupling. Read and modify these first.")
    lines.append("")

    for fp, cs in low_risk[:10]:
        short = _short_path(fp)
        avg_cc = getattr(cs, "avg_complexity", 0.0)
        coupling = getattr(cs, "coupling_score", 0)
        deg = in_deg.get(fp, 0)
        lines.append(
            f"- `{short}` — avg CC: {avg_cc:.1f} · coupling: {coupling} · "
            f"imported by: {deg} module(s)"
        )

    lines.append("")
    return "\n".join(lines) + "\n"


def _ac_ai_explanations(state: ArchaeonState) -> str:
    lines = ["## AI Explanations", ""]

    if not state.explanations:
        lines.append(
            "*LLM-generated architectural explanations were not included in this analysis.*"
        )
        lines.append("")
        return "\n".join(lines) + "\n"

    in_deg = _in_degree_map(state)
    sorted_exps = sorted(
        state.explanations.items(),
        key=lambda x: in_deg.get(x[0], 0),
        reverse=True,
    )

    for fp, explanation in sorted_exps[:15]:
        short = _short_path(fp)
        cs = state.complexity_scores.get(fp)
        risk_tag = f" · {getattr(cs, 'risk_level', '?')} risk" if cs else ""
        deg = in_deg.get(fp, 0)
        lines.append(f"### `{short}`{risk_tag} · in-degree: {deg}")
        lines.append("")
        lines.append(explanation.strip())
        lines.append("")

    return "\n".join(lines) + "\n"


# ═══════════════════════════════════════════════════════════════════════════
# agent_context.md — top-level assembler
# ═══════════════════════════════════════════════════════════════════════════

def generate_agent_context_doc(state: ArchaeonState) -> str:
    """
    Assemble agent_context.md from all _ac_* section generators.
    Concise by design — tables and bullets, not prose.
    Target use: paste as system context before asking an LLM to edit this repo.
    Every section is independently try/except wrapped.
    """
    repo = _repo_name(state)
    now = _timestamp()

    header = (
        f"# Repository Agent Context: `{repo}`\n\n"
        f"*Generated by Project Gnosis · {now} · {state.analysis_mode} mode*  \n"
        f"*Source: {state.repo_url} · Branch: {_default_branch(state)}*\n\n"
        f"> This document is optimised for AI coding agents.\n"
        f"> For human-readable documentation see `onboarding.md`.\n\n"
        f"---\n\n"
    )

    sections = [
        ("System Overview",             _ac_system_overview),
        ("Critical Entry Points",       _ac_critical_entry_points),
        ("Core Components",             _ac_core_components),
        ("Architectural Relationships", _ac_architectural_relationships),
        ("High Risk Areas",             _ac_high_risk_areas),
        ("Circular Dependencies",       _ac_circular_dependencies),
        ("Important Domain Objects",    _ac_important_domain_objects),
        ("Change Impact Guide",         _ac_change_impact_guide),
        ("Safe Starting Points",        _ac_safe_starting_points),
        ("AI Explanations",             _ac_ai_explanations),
    ]

    parts = [header]
    for name, fn in sections:
        try:
            parts.append(fn(state))
        except Exception as exc:
            logger.warning("agent_context.md: section '%s' failed: %s", name, exc)
            parts.append(f"## {name}\n\n*Section unavailable.*\n\n")

    parts.append(f"---\n\n*Project Gnosis · Code Archaeology Agent · {now}*\n")
    return "".join(parts)


# ═══════════════════════════════════════════════════════════════════════════
# Complexity report serialiser
# ═══════════════════════════════════════════════════════════════════════════

def generate_complexity_report_json(state: ArchaeonState) -> str:
    """
    Serialise complexity_scores to a JSON string for state.complexity_report_json.
    Uses actual ComplexityScore field names: parse_error, is_in_circular_dep.
    """
    report = {}
    for fp, cs in state.complexity_scores.items():
        report[fp] = {
            "risk_level": getattr(cs, "risk_level", "UNKNOWN"),
            "avg_complexity": getattr(cs, "avg_complexity", 0.0),
            "max_complexity": getattr(cs, "max_complexity", 0.0),
            "max_complexity_function": getattr(cs, "max_complexity_function", None),
            "coupling_score": getattr(cs, "coupling_score", 0),
            "parse_error": getattr(cs, "parse_error", False),
            "is_in_circular_dep": getattr(cs, "is_in_circular_dep", False),
            "risk_reasons": getattr(cs, "risk_reasons", []),
        }
    return json.dumps(report, indent=2)


# ═══════════════════════════════════════════════════════════════════════════
# Agent entry point
# ═══════════════════════════════════════════════════════════════════════════

def run(state: ArchaeonState) -> ArchaeonState:
    """
    Agent 7: Doc Generator.
    Called as doc_generator.run(state) by pipeline_runner.py.

    Writes three fields to state:
      state.final_doc              — onboarding.md content
      state.agent_context_md       — agent_context.md content
      state.complexity_report_json — complexity data as JSON string
    """
    logger.info("Doc Generator Agent: starting")

    # ── onboarding.md ────────────────────────────────────────────────────
    onboarding_sections = [
        _build_header,
        _build_project_summary,
        _build_repository_statistics,
        _build_architecture_map,
        _build_core_components,
        _build_tech_debt_report,
        _build_reading_order,
        _build_footer,
    ]
    parts = []
    for fn in onboarding_sections:
        try:
            parts.append(fn(state))
        except Exception as exc:
            logger.warning("onboarding.md: section '%s' failed: %s", fn.__name__, exc)

    state.final_doc = "".join(parts)
    logger.info("Doc Generator: onboarding.md complete (%d chars)", len(state.final_doc))

    # ── agent_context.md ─────────────────────────────────────────────────
    try:
        state.agent_context_md = generate_agent_context_doc(state)
        logger.info(
            "Doc Generator: agent_context.md complete (%d chars)",
            len(state.agent_context_md),
        )
    except Exception as exc:
        logger.error("Doc Generator: agent_context.md failed: %s", exc)
        state.agent_context_md = f"# Repository Agent Context\n\n*Generation failed: {exc}*\n"

    # ── complexity_report_json ────────────────────────────────────────────
    try:
        state.complexity_report_json = generate_complexity_report_json(state)
        logger.info("Doc Generator: complexity_report.json complete")
    except Exception as exc:
        logger.error("Doc Generator: complexity report failed: %s", exc)
        state.complexity_report_json = "{}"

    return state