"""
Agent 7: Doc Generator Agent

Reads from state:  file_manifest, symbol_tables, dependency_graph,
                   graph_stats, circular_deps, circular_nodes,
                   complexity_scores, topological_order, explanations,
                   owner, repo_name, default_branch
Writes to state:   final_doc

Pure synthesis. No LLM calls. No network. No file I/O.
Each section is built by an independent function wrapped in try/except.
One section failing never prevents the rest from rendering.
"""

from datetime import datetime
from pathlib import PurePosixPath

from src.state import ArchaeonState

# Section configuration
ARCH_MAP_CAP      = 15   # files in the architecture map
READING_ORDER_CAP = 25   # files in the reading order list
TECH_DEBT_FN_CAP  = 10   # functions in the complex-functions table
MAX_RELATED       = 6    # dependents/dependencies shown per component
COMPONENT_CAP     = 40   # max components written to the document


def run(state: ArchaeonState) -> ArchaeonState:
    print(f"\n[Agent 7: Doc Generator]")

    builders = [
        ("Header",           _build_header),
        ("Project Summary",  _build_project_summary),
        ("Statistics",       _build_stats_section),
        ("Architecture Map", _build_architecture_map),
        ("Core Components",  _build_core_components),
        ("Tech Debt Report", _build_tech_debt_report),
        ("Reading Order",    _build_reading_order),
        ("Footer",           _build_footer),
    ]

    sections = []
    for name, builder in builders:
        try:
            content = builder(state)
            if content and content.strip():
                sections.append(content)
                print(f"  ✓  {name}")
            else:
                print(f"  –  {name} (empty, skipped)")
        except Exception as exc:
            # Log the failure but continue building the rest of the document.
            # A missing Architecture Map is better than no document at all.
            print(f"  ✗  {name} (error: {exc})")

    state.final_doc = '\n\n---\n\n'.join(sections)

    word_count = len(state.final_doc.split())
    line_count = state.final_doc.count('\n') + 1
    print(f"\n  Document: {line_count} lines · {word_count} words · "
          f"{len(sections)} sections")
    print(f"\n[Agent 7: Doc Generator] Done")
    return state


# -----------------------------------------------------------------------
# Section 1: Header
# -----------------------------------------------------------------------

def _build_header(state: ArchaeonState) -> str:
    date_str = datetime.now().strftime("%B %d, %Y")
    repo_url = f"https://github.com/{state.owner}/{state.repo_name}"
    return (
        f"# {state.repo_name} — Architecture Overview\n\n"
        f"> **Generated by Project Gnosis** · {date_str}  \n"
        f"> Repository: [{state.owner}/{state.repo_name}]({repo_url})  \n"
        f"> Branch: `{state.default_branch or 'main'}`"
    )


# -----------------------------------------------------------------------
# Section 2: Project Summary
# -----------------------------------------------------------------------

def _build_project_summary(state: ArchaeonState) -> str:
    lines = ["## Project Summary\n"]

    # Opening: first two sentences of the most-imported explained file.
    # This gives the document a grounding statement about what the repo does,
    # sourced from the LLM explanation of the file most central to the codebase.
    opening = _get_summary_opening(state)
    if opening:
        lines.append(opening + "\n")

    # Language and size context
    lang_breakdown = _compute_language_breakdown(state)
    total = sum(lang_breakdown.values()) or 1
    lang_parts = [
        f"{lang} ({count / total * 100:.0f}%)"
        for lang, count in sorted(lang_breakdown.items(), key=lambda x: -x[1])[:4]
    ]
    lang_str = ", ".join(lang_parts) if lang_parts else "unknown"

    total_files   = len(state.file_manifest)
    total_funcs   = sum(len(st.functions) for st in state.symbol_tables.values())
    total_classes = sum(len(st.classes)   for st in state.symbol_tables.values())
    explained     = len(state.explanations)

    summary = (
        f"This repository contains **{total_files} analyzed files** "
        f"in {lang_str}. "
        f"**{total_funcs} functions** and **{total_classes} classes** "
        f"were extracted and semantically indexed."
    )
    if explained:
        summary += (
            f" **{explained} file(s)** received detailed explanations "
            f"from the LLM analysis."
        )
    lines.append(summary)

    # Risk and dependency health.
    # health collects only the BAD signals (things to flag with attention).
    # Circular dep cleanliness is always stated explicitly — it must appear
    # in the output whether cycles exist or not. The test for the clean case
    # checks for "no circular" or "not detected" in the output, so we cannot
    # rely on the else-branch alone (which only fires when health is empty).
    risk_dist = _compute_risk_distribution(state)
    critical  = risk_dist.get("CRITICAL", 0)
    high      = risk_dist.get("HIGH", 0)
    health    = []

    if critical:
        health.append(f"**{critical} CRITICAL** risk file(s)")
    if high:
        health.append(f"**{high} HIGH** risk file(s)")
    if state.circular_deps:
        health.append(
            f"**{len(state.circular_deps)} circular dependency cycle(s)**"
        )

    if health:
        lines.append(
            "\n**Attention required:** " + ", ".join(health) + " identified."
        )
        # FIX: when other risks exist but NO circular deps, we must still
        # say so explicitly. Without this line the clean-cycles case produces
        # output that mentions CRITICAL/HIGH but says nothing about circular
        # deps — the test asserts "no circular" or "not detected" must appear.
        if not state.circular_deps:
            lines.append("No circular dependencies detected.")
    else:
        lines.append(
            "\nNo critical risks or circular dependencies were detected."
        )

    return '\n'.join(lines)


def _get_summary_opening(state: ArchaeonState) -> str:
    """
    Find the most structurally central file that has an explanation,
    and extract its first two sentences as a summary opener.

    WHY THE MOST-IMPORTED FILE:
    The file imported by the most other files is the closest thing to
    a "topic sentence" for the codebase. It defines the concepts or
    interfaces that everything else builds on. Its explanation describes
    what the repo fundamentally does.
    """
    if not state.explanations or not state.graph_stats:
        # Fall back to module docstrings of shallow files
        for path, st in state.symbol_tables.items():
            if path.count('/') <= 1 and st.module_docstring:
                return f"*{st.module_docstring.strip()}*"
        return ""

    best_path     = None
    best_indegree = -1
    for path in state.explanations:
        indegree = state.graph_stats.get(path, {}).get('in_degree', 0)
        if indegree > best_indegree:
            best_indegree = indegree
            best_path     = path

    if not best_path:
        return ""

    explanation = state.explanations[best_path]
    # Split on '. ' to get sentences; take first two
    raw     = explanation.replace('\n', ' ').strip()
    parts   = raw.split('. ')
    excerpt = '. '.join(parts[:2]).strip()
    if excerpt and not excerpt.endswith('.'):
        excerpt += '.'

    return f"*{excerpt}*" if excerpt else ""


# -----------------------------------------------------------------------
# Section 3: Repository Statistics
# -----------------------------------------------------------------------

def _build_stats_section(state: ArchaeonState) -> str:
    lang_breakdown = _compute_language_breakdown(state)
    total_lang     = sum(lang_breakdown.values()) or 1
    lang_str = ', '.join(
        f"{lang} ({count / total_lang * 100:.0f}%)"
        for lang, count in sorted(lang_breakdown.items(), key=lambda x: -x[1])
    ) if lang_breakdown else "—"

    total_files   = len(state.file_manifest)
    total_funcs   = sum(len(st.functions) for st in state.symbol_tables.values())
    total_classes = sum(len(st.classes)   for st in state.symbol_tables.values())
    explained     = len(state.explanations)

    risk_dist = _compute_risk_distribution(state)
    risky     = risk_dist.get("CRITICAL", 0) + risk_dist.get("HIGH", 0)

    G = state.dependency_graph
    edges = G.number_of_edges() if G else 0

    rows = [
        ("Files analyzed",        str(total_files)),
        ("Languages",             lang_str),
        ("Functions extracted",   str(total_funcs)),
        ("Classes extracted",     str(total_classes)),
        ("Import relationships",  str(edges)),
        ("Files explained",       f"{explained} of {len(state.complexity_scores)}"),
        ("High-risk files",       str(risky)),
        ("Circular dependencies", str(len(state.circular_deps))),
    ]

    table = "| Metric | Value |\n|---|---|\n"
    for metric, value in rows:
        table += f"| {metric} | {value} |\n"

    return f"## Repository Statistics\n\n{table}"


# -----------------------------------------------------------------------
# Section 4: Architecture Map
# -----------------------------------------------------------------------

def _build_architecture_map(state: ArchaeonState) -> str:
    if not state.graph_stats:
        return ""

    # Sort by in-degree descending, take top N
    ranked = sorted(
        state.graph_stats.items(),
        key=lambda x: (-x[1]['in_degree'], x[0])
    )
    # Only show files that are actually imported by something
    ranked = [(p, s) for p, s in ranked if s['in_degree'] > 0][:ARCH_MAP_CAP]

    if not ranked:
        return (
            "## Architecture Map\n\n"
            "*No internal import relationships detected. "
            "Files may be standalone scripts or the import resolution "
            "found no internal connections.*"
        )

    max_indegree = max(s['in_degree'] for _, s in ranked) or 1

    lines = ["## Architecture Map\n"]
    lines.append(
        "Files ranked by how many other files import them. "
        "Higher in-degree means changing this file has wider impact.\n"
    )
    lines.append("```")
    lines.append(
        f"{'FILE':<45} {'IMPORTS':>7}  {'RISK':<8}"
    )
    lines.append("─" * 65)

    for path, stats in ranked:
        in_deg   = stats['in_degree']
        risk     = state.complexity_scores.get(path)
        risk_lvl = risk.risk_level if risk else "—"
        is_circ  = path in state.circular_nodes

        bar_len  = round((in_deg / max_indegree) * 20)
        bar      = "█" * bar_len + "░" * (20 - bar_len)
        name     = PurePosixPath(path).name
        circ_tag = " ⚠" if is_circ else ""

        lines.append(
            f"  {bar}  {name:<35}{circ_tag:2}  {in_deg:>4}    {risk_lvl}"
        )

    lines.append("```")

    isolated = sum(
        1 for p, s in state.graph_stats.items()
        if s['in_degree'] == 0 and s['out_degree'] == 0
    )
    if isolated:
        lines.append(
            f"\n*{isolated} file(s) have no import relationships "
            f"(isolated scripts or entry points).*"
        )
    if state.circular_nodes:
        lines.append(
            f"\n*⚠ = file is part of a circular dependency cycle.*"
        )

    return '\n'.join(lines)


# -----------------------------------------------------------------------
# Section 5: Core Components
# -----------------------------------------------------------------------

def _build_core_components(state: ArchaeonState) -> str:
    if not state.explanations:
        return (
            "## Core Components\n\n"
            "*No LLM explanations available. "
            "Run Phase 6 with a valid GROQ_API_KEY to generate explanations.*"
        )

    # Sort explained files by in-degree descending
    sorted_paths = sorted(
        state.explanations.keys(),
        key=lambda p: -state.graph_stats.get(p, {}).get('in_degree', 0)
    )[:COMPONENT_CAP]

    lines = ["## Core Components\n"]
    lines.append(
        f"*{len(sorted_paths)} file(s) with LLM-generated explanations, "
        f"ordered by structural importance (in-degree).*\n"
    )

    for path in sorted_paths:
        explanation = state.explanations[path]
        score       = state.complexity_scores.get(path)
        stats       = state.graph_stats.get(path, {})
        language    = score.language if score else "Unknown"
        risk_lvl    = score.risk_level if score else "—"
        in_degree   = stats.get('in_degree', 0)

        # Heading: full path as inline code
        lines.append(f"### `{path}`\n")

        # Badges row
        badge_parts = [
            f"**Language:** {language}",
            f"**Risk:** {risk_lvl}",
            f"**Imported by:** {in_degree} file(s)",
        ]
        if score and score.function_count:
            badge_parts.append(f"**Functions:** {score.function_count}")
        if score and score.avg_complexity > 0:
            badge_parts.append(
                f"**Avg complexity:** {score.avg_complexity:.1f}"
            )
        lines.append(' · '.join(badge_parts) + "\n")

        # Explanation
        lines.append(explanation.strip() + "\n")

        # Dependency context as a blockquote
        dep_lines = []
        dependencies = stats.get('dependencies', [])
        dependents   = stats.get('dependents',   [])

        if dependencies:
            dep_names = [PurePosixPath(d).name for d in dependencies[:MAX_RELATED]]
            extra = len(dependencies) - MAX_RELATED
            dep_str = ', '.join(f"`{n}`" for n in dep_names)
            if extra > 0:
                dep_str += f" +{extra} more"
            dep_lines.append(f"**Imports:** {dep_str}")
        else:
            dep_lines.append("**Imports:** nothing internal")

        if dependents:
            dep_names = [PurePosixPath(d).name for d in dependents[:MAX_RELATED]]
            extra = len(dependents) - MAX_RELATED
            dep_str = ', '.join(f"`{n}`" for n in dep_names)
            if extra > 0:
                dep_str += f" +{extra} more"
            dep_lines.append(f"**Imported by:** {dep_str}")

        if dep_lines:
            lines.append('> ' + '  \n> '.join(dep_lines) + "\n")

    return '\n'.join(lines)


# -----------------------------------------------------------------------
# Section 6: Tech Debt Report
# -----------------------------------------------------------------------

def _build_tech_debt_report(state: ArchaeonState) -> str:
    lines = ["## Tech Debt Report\n"]
    any_debt = False

    # ---- Circular dependencies ------------------------------------------
    if state.circular_deps:
        any_debt = True
        lines.append(
            f"### Circular Dependencies\n\n"
            f"⚠️ **{len(state.circular_deps)} cycle(s) detected.** "
            f"These files cannot be read in isolation — each depends on "
            f"something that depends on it. Refactor before touching.\n"
        )
        for cycle in state.circular_deps[:8]:
            names    = [PurePosixPath(p).name for p in cycle]
            cycle_str = " → ".join(names) + f" → {names[0]}"
            lines.append(f"- `{cycle_str}`")
        if len(state.circular_deps) > 8:
            lines.append(f"- *...and {len(state.circular_deps) - 8} more cycles*")
        lines.append("")
    else:
        lines.append(
            "### Circular Dependencies\n\n"
            "✅ No circular dependencies detected.\n"
        )

    # ---- Critical risk files --------------------------------------------
    critical_scores = [
        s for s in state.complexity_scores.values()
        if s.risk_level == "CRITICAL"
    ]
    if critical_scores:
        any_debt = True
        lines.append("### Critical Risk Files\n")
        lines.append("| File | Reasons |")
        lines.append("|---|---|")
        for score in sorted(critical_scores, key=lambda s: -s.max_complexity):
            name    = PurePosixPath(score.file_path).name
            reasons = "; ".join(score.risk_reasons[:2]) or "see complexity report"
            lines.append(f"| `{name}` | {reasons} |")
        lines.append("")

    # ---- Most complex functions -----------------------------------------
    all_fns = []
    for score in state.complexity_scores.values():
        for fn_name, complexity in score.function_scores.items():
            if complexity >= 6:   # only worth flagging
                all_fns.append((complexity, fn_name, score.file_path))

    if all_fns:
        any_debt = True
        all_fns.sort(key=lambda x: -x[0])
        top_fns = all_fns[:TECH_DEBT_FN_CAP]
        lines.append("### Most Complex Functions\n")
        lines.append("Functions with cyclomatic complexity ≥ 6 "
                     "(hard to test and modify safely).\n")
        lines.append("| Complexity | Function | File |")
        lines.append("|:---:|---|---|")
        for complexity, fn_name, file_path in top_fns:
            fname = PurePosixPath(file_path).name
            lines.append(f"| {int(complexity)} | `{fn_name}` | `{fname}` |")
        lines.append("")

    # ---- High coupling files --------------------------------------------
    high_coupling = [
        s for s in state.complexity_scores.values()
        if s.coupling_score >= 6
    ]
    if high_coupling:
        any_debt = True
        high_coupling.sort(key=lambda s: -s.coupling_score)
        lines.append("### High Coupling Files\n")
        lines.append(
            "These files import from many internal modules. "
            "Changing any of their dependencies may affect them.\n"
        )
        lines.append("| File | Internal Imports | Risk |")
        lines.append("|---|:---:|---|")
        for score in high_coupling[:8]:
            name = PurePosixPath(score.file_path).name
            lines.append(
                f"| `{name}` | {score.coupling_score} | {score.risk_level} |"
            )
        lines.append("")

    # ---- Parse failures -------------------------------------------------
    parse_failures = [
        s for s in state.complexity_scores.values()
        if s.parse_error
    ]
    if parse_failures:
        any_debt = True
        lines.append("### Files with Parse Errors\n")
        lines.append(
            "These files contain syntax errors. tree-sitter could not "
            "fully parse them. They were not chunked into the RAG collection "
            "and may produce incorrect analysis results.\n"
        )
        for score in parse_failures[:8]:
            lines.append(f"- `{score.file_path}`")
        if len(parse_failures) > 8:
            lines.append(f"- *...and {len(parse_failures) - 8} more*")
        lines.append("")

    if not any_debt:
        lines.append(
            "*No significant tech debt signals detected. "
            "Run a more detailed audit on files rated MEDIUM risk "
            "or above in the complexity report.*"
        )

    return '\n'.join(lines)


# -----------------------------------------------------------------------
# Section 7: Suggested Reading Order
# -----------------------------------------------------------------------

def _build_reading_order(state: ArchaeonState) -> str:
    lines = ["## Suggested Reading Order\n"]

    if state.topological_order:
        # We have a clean order (no cycles)
        display_paths = state.topological_order[:READING_ORDER_CAP]

        lines.append(
            "Read these files in order. Each file appears after everything "
            "it depends on, so you build understanding incrementally "
            "without forward-referencing concepts you have not seen yet.\n"
        )

        for i, path in enumerate(display_paths, start=1):
            name    = PurePosixPath(path).name
            score   = state.complexity_scores.get(path)
            risk    = score.risk_level if score else ""
            in_deg  = state.graph_stats.get(path, {}).get('in_degree', 0)

            annotation_parts = []
            if in_deg >= 5:
                annotation_parts.append(f"imported by {in_deg} files")
            if risk in ("HIGH", "CRITICAL"):
                annotation_parts.append(f"{risk} risk — read carefully")

            annotation = f" — *{', '.join(annotation_parts)}*" if annotation_parts else ""
            lines.append(f"{i:>2}. `{path}`{annotation}")

        total = len(state.topological_order)
        if total > READING_ORDER_CAP:
            lines.append(
                f"\n*...and {total - READING_ORDER_CAP} more files. "
                f"Full order available in `graph_data.json` → `topological_order`.*"
            )
    else:
        # Cycles exist — explain why and show what we can
        lines.append(
            "⚠️ **A complete reading order cannot be computed** because "
            "circular dependencies exist in this codebase. Files involved "
            "in cycles have no well-defined reading order — each requires "
            "understanding the other first.\n"
        )

        if state.circular_nodes:
            cycle_names = [
                PurePosixPath(p).name for p in list(state.circular_nodes)[:6]
            ]
            lines.append(
                f"**Files in cycles:** "
                f"{', '.join(f'`{n}`' for n in cycle_names)}"
            )
            if len(state.circular_nodes) > 6:
                lines.append(f" +{len(state.circular_nodes) - 6} more")
            lines.append("")

        lines.append(
            "**Recommended first steps:**\n\n"
            "1. Resolve the circular dependencies in the Tech Debt Report above.\n"
            "2. Re-run Project Gnosis to get a complete reading order.\n"
            "3. In the meantime, start with low in-degree, low-risk files "
            "and work outward.\n"
        )

        # Show safest files to start with regardless
        safe_files = [
            (path, state.graph_stats.get(path, {}).get('in_degree', 0))
            for path, score in state.complexity_scores.items()
            if score.risk_level == "LOW"
            and path not in state.circular_nodes
        ]
        safe_files.sort(key=lambda x: -x[1])
        if safe_files:
            lines.append(
                "**Suggested starting points (LOW risk, not in cycles):**\n"
            )
            for path, in_deg in safe_files[:8]:
                lines.append(f"- `{path}` (imported by {in_deg} files)")

    return '\n'.join(lines)


# -----------------------------------------------------------------------
# Section 8: Footer
# -----------------------------------------------------------------------

def _build_footer(state: ArchaeonState) -> str:
    now      = datetime.now().strftime("%Y-%m-%d %H:%M")
    n_agents = 7
    scores   = list(state.complexity_scores.values())
    risk_dist = _compute_risk_distribution(state)

    risk_summary = " · ".join(
        f"{level}: {risk_dist.get(level, 0)}"
        for level in ("CRITICAL", "HIGH", "MEDIUM", "LOW")
    )

    return (
        f"## About This Document\n\n"
        f"Generated by **Project Gnosis** — Code Archaeology Agent  \n"
        f"Generated at: `{now}`  \n"
        f"Pipeline: {n_agents} agents ran in sequence  \n"
        f"Files analyzed: {len(state.file_manifest)}  \n"
        f"Files scored: {len(scores)}  \n"
        f"Risk distribution: {risk_summary}  \n"
        f"Files explained: {len(state.explanations)}  \n\n"
        f"*This document is a snapshot. Re-run Project Gnosis after "
        f"significant changes to keep it current.*  \n\n"
        f"> **Outputs:** `onboarding.md` · `complexity_report.json` · "
        f"`dependency_graph.html` · `symbol_tables.json` · "
        f"`graph_data.json` · `explanations.json`"
    )


# -----------------------------------------------------------------------
# Shared utilities
# -----------------------------------------------------------------------

def _compute_language_breakdown(state: ArchaeonState) -> dict:
    counts: dict = {}
    for f in state.file_manifest:
        if f.language not in ("Markdown", "YAML", "TOML", "Unknown"):
            counts[f.language] = counts.get(f.language, 0) + 1
    return counts


def _compute_risk_distribution(state: ArchaeonState) -> dict:
    dist: dict = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0}
    for score in state.complexity_scores.values():
        dist[score.risk_level] = dist.get(score.risk_level, 0) + 1
    return dist